apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-input-pv-app
  # namespace: app
spec:
  storageClassName: manual
  capacity:
    storage: 1000Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data     # Host directory to mount
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-input-pvc
  namespace: app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi  # Must match PV size
  volumeName: image-input-pv-app
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: image-input-pv-argo
  # namespace: argo
spec:
  storageClassName: manual
  capacity:
    storage: 1000Gi  # Adjust size as needed
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data     # Host directory to mount
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-input-pvc
  namespace: argo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi  # Must match PV size
  volumeName: image-input-pv-argo
---
