apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-engine-env-configmap
  labels:
    app: inference-engine-app
  namespace: app
data:
  INPUT_DIRECTORY: "/input/"
  TOKEN_PATH: "/var/run/secrets/tokens/token"
  BASE_IMAGE_PATH: "/mnt/data/inputs/"
  ARGO_WORKFLOW_YAML_PATH: "/mnt/data/ml-platform/containers"
  ARGO_WORKFLOW_API_URL: "http://argo-workflows-server.argo.svc.cluster.local:2746/api/v1/workflows/argo"
---