apiVersion: v1
kind: ConfigMap
metadata:
  name: inference-engine-env-configmap
  labels:
    app: inference-engine-app
  namespace: app
data:
  ARGO_WORKFLOW_API_URL: "https://argo-workflows-server.argo.svc.cluster.local:2746/api/v1/workflows/argo" # new flow
  # ARGO_WORKFLOW_API_URL: "https://argo-server.argo.svc.cluster.local:2746/api/v1/workflows/argo" # old flow
  ARGO_WORKFLOW_YAML_PATH: "/mnt/pipeline-configs/"
  INPUT_DIRECTORY: "/input/"
  TOKEN_PATH: "/var/run/secrets/tokens/token"
---