FROM python:3.11.13-slim AS builder

RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    rm -rf /var/lib/apt/lists/*


COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

FROM python:3.11.13-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends libgomp1 && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /usr/local/lib/python3.11 /usr/local/lib/python3.11
COPY --from=builder /usr/local/bin /usr/local/bin

WORKDIR /app

# inference-engine-fastapi-env:python-3.11.13-slim
# minikube image build -f Dockerfile-env -t inference-engine-fastapi-env:python-3.11.13-slim .
# docker tag inference-engine-fastapi-env:python-3.11.13-slim us-central1-docker.pkg.dev/utilities-vision/uvision-kubernetes-deployment/inference-engine-fastapi-env:python-3.11.13-slim