apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
    generateName: ml-workflow-
spec:
    imagePullSecrets:
    - name: artifact-registery-secret
    entrypoint: main-dag
    arguments:
      parameters:
      - name: folder_name
      - name: windmill-damages
        value: "true"

    volumes:
        - name: infengine-data
          persistentVolumeClaim:
            claimName: host-mnt-pvc
        - name: input-data
          persistentVolumeClaim:
            claimName: image-input-pvc

    templates:
          - name: main-dag
            dag:
                tasks:
                  # Level 1: 5 parallel jobs
                  - name: windmill-damages
                    template: detectron2-template
                    when: "{{workflow.parameters.windmill-damages}} == true"
                    arguments:
                        parameters: 
                        - name: src
                          value: "/input/{{workflow.parameters.folder_name}}/"
                        - name: dest
                          value: "/input/{{workflow.parameters.folder_name}}/output/"
                        - name: assets
                          value: '{{workflow.parameters.assets}}'
                        - name: grouped_assets
                          value: '[]'                            
                        - name: config
                          value: "/mnt/pipeline-configs/windmill/windmill_damage.json"
                        - name: start_msg
                          value: '["dirt", "damage"]'
                        - name: end_msg
                          value: '[]'
                  

                  #  automate ----------------------------------

                  - name: automate-report-generation
                    template: automate-report-generation-template
                    depends: "windmill-damages"

                    arguments:
                        parameters: 
                        - name: src
                          value: "/input/{{workflow.parameters.folder_name}}/"
                        - name: dest
                          value: "/input/{{workflow.parameters.folder_name}}/output/"
                        - name: config
                          value: "/mnt/pipeline-configs/windmill/automate.json"
                        - name: start_msg
                          value: '[]'
                        - name: end_msg
                          value: '["Celery Job"]'
                        


          - name: detectron2-template
            inputs:
                parameters:
                    - name:  src
                    - name:  dest
                    - name:  assets     
                    - name:  grouped_assets                    
                    - name:  config
                    - name:  start_msg
                    - name:  end_msg

            imagePullSecrets:
            - name: artifact-registery-secret

            container:
                # image: us-central1-docker.pkg.dev/utilities-vision/uvision-kubernetes-deployment/detectron2-cli-input:python-3.12.11-cuda-12.1.1-cudnn8-runtime-ubuntu22.04  # Replace with your ML job image
                image: us-central1-docker.pkg.dev/utilities-vision/uvision-kubernetes-deployment/test/detectron2-cli-input:python-3.12.11-cuda-12.1.1-cudnn8-runtime-ubuntu22.04  # Replace with your ML job image
                # image: detectron2-cli-input:python-3.12.11-slim-bookworm  # Replace with your ML job image
                imagePullPolicy: Always
                command: ["python", "detectron2_inference.py"]
                args: ["--src","{{inputs.parameters.src}}", "--dest","{{inputs.parameters.dest}}", "--assets","{{inputs.parameters.assets}}", "--grouped_assets","{{inputs.parameters.grouped_assets}}", "--config","{{inputs.parameters.config}}", "--workflow_name", "{{workflow.name}}", "--folder_name", "{{workflow.parameters.folder_name}}", "--start_msg", "{{inputs.parameters.start_msg}}", "--end_msg", "{{inputs.parameters.end_msg}}"]
                volumeMounts:
                    - name: infengine-data
                      mountPath: /mnt
                    - name: input-data
                      mountPath: /input
                      
                envFrom:
                    - secretRef:
                        name: uvision-ia-frontend-database-secret
                    - secretRef:
                        name: uvision-database-secret                           
                #         key: api-key
                    # - name: gcs-bucket
                    #   mountPath: /mnt/gcs


          - name: automate-report-generation-template
            inputs:
                parameters:
                    - name:  src
                    - name:  dest
                    - name:  config
                    - name:  start_msg
                    - name:  end_msg
                    
            container:
                image: us-central1-docker.pkg.dev/utilities-vision/uvision-kubernetes-deployment/automate-cli-input:python-3.12.11-slim-bookworm   # Replace with your ML job image
                imagePullPolicy: Always
                command: ["python", "automate.py"]
                args: ["--src","{{inputs.parameters.src}}", "--dest","{{inputs.parameters.dest}}", "--config","{{inputs.parameters.config}}", "--start_msg", "{{inputs.parameters.start_msg}}", "--end_msg", "{{inputs.parameters.end_msg}}", "--folder_name", "{{workflow.parameters.folder_name}}"]
                volumeMounts:
                    - name: infengine-data
                      mountPath: /mnt
                    - name: input-data
                      mountPath: /input
                envFrom:
                    - secretRef:
                        name: uvision-ia-frontend-database-secret
                    # - name: gcs-bucket
                    #   mountPath: /mnt/gcs

    
# inputs:
            #     parameters:
            #     - name: node-name